### ISSUE TITLE
유효하지 않은 상품 코드로 상품 상세 조회 시 안드로이드 native SDK와 다르게 처리되는 문제

### ISSUE THREAD

**Issue by npcdja** [ONE-store/flutter_plugins#2]
# 문제 상황
Flutter용 SDK에서는 유효하지 않은 상품 코드로 상품 상세 조회를 시도할 경우 응답 코드는 `PurchaseResponse.ok (0)`, 아이템 목록은 empty로 반환되는데요. 안드로이드 native SDK에서는 `ResponseCode.RESULT_ERROR (6)`로 오류 응답이 내려옵니다.
<img width="1473" alt="상품 상세 정보 query 결과" src="https://github.com/user-attachments/assets/08dccf42-3bb7-4a86-a68d-e116730ce040">

단순히 응답 정보만 다른 것이 아니라 UI 처리에서도 다른 결과가 나타나는데요. Flutter SDK에서는 별다른 UI 액션이 없지만, 안드로이드 native SDK에서는 아래와 같이 구매 실패 화면이 나타납니다.
<img width="323" alt="유효하지 않은 상품 코드로 결제 시도 시 실패 화면" src="https://github.com/user-attachments/assets/dc415b12-e376-444b-af0e-31c444adc6db">

사소한 이슈이긴 하나, 기대 결과는 SDK 상호간 동일해야 한다고 판단되어 이슈 제보드립니다.

# 예시 코드
```dart
class Example {
  final _authClient = OneStoreAuthClient();
  final _clientManager = PurchaseClientManager.instance;

  void playground() async {
    _init();

    await _oneStoreSignin();

    final queryResult = await _clientManager.queryProductDetails(
      productIds: ["<원스토어에 등록되지 않은 허상의 상품 아이디>"],
      productType: ProductType.inapp,
    );

    print("responseCode: ${queryResult.iapResult.responseCode}"); // PurchaseResponse.ok (0);
    print("itemList: ${queryResult.productDetailsList}"); // []
  }

  void _init() {
    _clientManager.initialize("<원스토어 라이선스 키>");
  }

  Future<void> _oneStoreSignIn() async {
    final result = await _authClient.launchSignInFlow();
    if (!result.isSuccess()) {
      print("원스토어 로그인 실패");
    }

    print("원스토어 로그인 성공");
  }
}
```

flutter_onestore_inapp Version
0.3.0

Flutter Version
Flutter 3.24.3

Dart Version
Dart 3.5.3

기기 환경
안드로이드 에뮬레이터 Android 14.0

개발하기 편하게 SDK를 제작해주셔서 감사합니다.

**Comment by ONEstore-developer** [comment]
@npcdja 님
문의해 주신 **Flutter Plugin과 Java SDK에서 유효하지 않은 상품 코드를 사용해 상품 상세 정보를 요청했을 때의 응답 차이**에 대해 확인하였습니다. 테스트를 진행한 결과, 두 SDK 모두 동일하게 아래와 같은 응답을 반환하는 것을 확인하였습니다:

• responseCode: 0
• 상품 목록: empty list

두 번째 스크린샷은 유효하지 않은 상품 코드로 **구매 요청**을 하여 노출되는 UI 입니다.
Flutter Plugin과 Java SDK를 적용한 앱내에 API 후 처리 로직이 다른 것으로 보입니다.
